hypno_colors = {
    "Wake": "#62e273",
    "Brief-Arousal": "chartreuse",
    "Transition-to-NREM": "lightskyblue",
    "Transition-to-Wake": "palegreen",
    "NREM": "cornflowerblue",
    "Transition-to-REM": "plum",
    "REM": "magenta",
    "Transition": "grey",
    "Art": "crimson",
    "Wake-art": "crimson",
    "Unsure": "white",
    "Good": "lime",
    #"Wake-Good": "turquoise",
    "Wake-Good": "#62e273",
    "Sort-Exclude": "coral",
}
